services:
  mc:
    build: ./Server
    environment:
      - DATABASE_URI=mongodb://mongo:27017
      - TEBEX_SECRET=ZfGR4j0CWqDrKmvpgEU7UkGErS5i8ck5
      - JWT_SECRET=boobs
    volumes:
      - .:/Production
      - ./certs:/certs:ro
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "19132:19132/udp"
      - "8080:8080"
      - "6060:6060"
    depends_on:
      - mongo

  mongo:
    container_name: mongodb-brb
    image: mongo:8
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo:/data/db

volumes:
  mongo:
